### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by agn-fj** [kevinohara80/nforce-metadata#3]
Kevin - thanks for all of the nforce stuff - it's great!

Any advice on dealing with this error when authenticating?
- "Error: Hostname/IP doesn't match certificate's altnames"

I can get around it via the flag below, but is there a better way?

``` javascript
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';
```

Thanks again -

**Comment by kevinohara80** [comment]
Sorry for the delayed response. You caught me during a busy travel time, then vacation!

I really don't know why you'd be getting that error. The underlying node-soap module might be causing it. I'm guessing your workaround is the best way for now. If I get a chance, I'll poke around and see if there is something that I can expose to be configurable.

**Comment by agn-fj** [comment]
No problem at all - thanks for all of the effort on nforce! It's awesome.

**Comment by kevinohara80** [comment]
Glad you like it! I'm going to close this for now but I'll respond here if I find out anything new.
