### ISSUE TITLE
How to work behind proxy with listMetadata

### ISSUE THREAD

**Issue by gaikwadrahul20** [kevinohara80/nforce-metadata#8]
I use the below code
`...
org.meta.listMetadata({ 'queries': types, 'requestOpts': {timeout: 6000, proxy: {hostname:'some_address',port:'someport'}}}).then(
.....`
Although if we pass proxy like above to authenticate function of nforce package it is working. Here it is not.

**Comment by kevinohara80** [comment]
I think this needs to be handled in the soap client and exposed as an option in the nforce-metadata api. Would you want to take a stab at it?

**Comment by kevinohara80** [comment]
There looks to be a solution here: https://stackoverflow.com/questions/36057607/calling-soap-api-through-proxy-with-node-soap-client

**Comment by gaikwadrahul20** [comment]
@kevinohara80 Thank you so much Kevin `process.env.http_proxy` solved my problem. Also SOAP client can also be helpful.
